### ISSUE TITLE
Improved launcher approach

### ISSUE THREAD

**Issue by raziel2001au** [mccoy88f/JDownloader-Launcher-M1-ARM64#1]
I feel like you're over complicating things. You just need a simple shell script within an app, just make sure the script is named the same as the app itself and it should execute, for example, your script would be located at:
JDownloader.app/JDownloader

The script I did for example contains the following:
#!/bin/bash
java -jar ~/Library/Application\ Support/JDownloader/JDownloader\ 2/JDownloader.jar

I'll attach an example I created. This simple approach solves several problems with your launcher:
1) The app in the dock is called JDownloader, not java
2) If you have the launcher in the dock, it won't open JDownloader as a separate dock icon, it will run the app using the existing dock icon
3) It's just simpler and the app behaves the way you would expect it to

[JDownloaderLauncher.zip](https://github.com/mccoy88f/JDownloader-Launcher-M1-ARM64/files/7775475/JDownloaderLauncher.zip)

**Comment by mccoy88f** [comment]
Thanks a lot.
Using your version i update the app.
Thanks

**Comment by raziel2001au** [comment]
All good, the only funny thing I've noticed is that when it updates, it will launch the intel version again, so you have to close that and reopen it for the Apple Silicon version. But I think that's unavoidable, it's likely just how the updater works.

**Comment by piratx** [comment]
It doesnt work on M1 Monterey. I had to check the script and change the path but its only working if you click the binary/script file it works.. :) Thanks in advance!

**Comment by raziel2001au** [comment]
> It doesnt work on M1 Monterey. I had to check the script and change the path but its only working if you click the binary/script file it works.. :) Thanks in advance!

I'm using Monterey and it definitely works. The wrapper is about as straight forward as it gets and uses a feature which has existed in MacOS for many years: if you have a Test.app and there's an executable shell script matching the name of the app, in this case 'Test', it will execute that script using the shell specified on the first line.

You likely changed the name of the app so it no longer matches the name of the script file, or altered one of the executable flags, or removed the first line in the script which tells it what shell to use to execute the script.

**Comment by piratx** [comment]
Hello,
Nothing of this. I just placed the app (which is semi complete for the .app file structure) in inside the JDownloader 2.0 folder. 
 
In the. .app folder you need an info.plist file which tells you where and which of the files inside .app is the executable. In this case the .app only have a binary/script inside it which is shebangs and a line with the path of jar executable file that you need to run jdownloader. And that path isnt there for me. Its either on ~/bin/Jdownloader/ or in ~/ Applications/jdownloader. 

Please let me know if I am doing anything wrong and thanks again for this one!

.)

**Comment by raziel2001au** [comment]
I have no idea what you're trying to do, but it doesn't sound right. You don't need an info.plist using the method here. If you create an app with an executable shell script with the same name as the app, it will execute the script using the shell specified in the script file. This is standard Mac OS functionality.

I don't think anyone has tried putting the JDownloader.app in the same folder as the JDownloader 2.0 installation. It would probably work, but it just sounds like you're missing something.

This is how I have it set up:
* I have an Apple Silicon compatible version of Java installed, it won't work without this.
* JDownloader is installed to my application support directory (I use the official JDownloader installer for Intel Macs, the other OS download would probably work, but I haven't tried it myself)
* The JDownloader jars are located in the following directory for me as a result: ~/Library/Application Support/JDownloader/JDownloader 2
* JDownloader.app is placed in /Applications
* Within the JDownloader.app, the 'JDownloader' script has the following content:
```
#!/bin/bash
java -jar ~/Library/Application\ Support/JDownloader/JDownloader\ 2/JDownloader.jar
```

So it's just running my custom installed version of Java and telling it to run the JDownloader jar. The download by mccoy88f from here recommends installing JDownloader somewhere else (I think in the Applications directory), but I prefer it being out of the way, which is why I install it to application support. But there's no need to replace anything in the JDownloader installation directory, the JDownloader.app is just a basic shell script that runs JDownloader using your installed copy of Java.

I just noticed you saying "that path isn't there for me". You obviously need to update the shell script to point to where you have installed JDownloader or it's not going to work.

**Comment by raziel2001au** [comment]
I'll also add that you should have created a separate issue for your problem.

**Comment by piratx** [comment]
Sorry about that :(
Can you move it or can I do it somehow?

Cool, will try this again then.

I have installed: zulu17.32.13-ca-jdk17.0.2-macosx_aarch64.dmg first.
I am installing Jdownloader just the way it is. No changes or anything on the installer.
So it always using my ~/Applications directory

Thank you!

**Comment by raziel2001au** [comment]
I don't think it can be moved.

The key to remember is that this is just a launcher app, you still need to set up Java/JDownloader and your startup script needs to be correct. Alternatively just follow mccoy88f's instructions to the letter, then you don't need to alter the script at all since JDownloader will already be in the right place.

There are things to keep in mind if you do alter the script, for example, spaces in the path need an escape \ character. I'd also recommend extracting a clean version of the app so you know everything has the correct execute bits set and such.

That's about the amount of help I can offer. I'm going to close this issue. If you need more help, open a separate issue.
